add mysql replication lag detector
claranet/terraform-signalfx-detectors pull request #125
Opened 2020-09-29 12:17 UTC by frederic-peraud

@BzSpi @Shr3ps @xp-1000 

Add Azure Mysql Replication Lag detector based on SignalFX `seconds_behind_master` metric.

2020-09-29 12:27 UTC, xp-1000 commented on cloud/azure/mysql/detectors-mysql.tf
> +    description           = "is too high > ${var.replication_lag_threshold_critical}"
you can add unit if you want

2020-09-29 12:28 UTC, xp-1000 commented on cloud/azure/mysql/detectors-mysql.tf
> +  name = "${join("", formatlist("[%s]", var.prefixes))}[${var.environment}] Azure MySQL Replication Lag"
keep "replication lag" in lower case please

2020-09-29 12:29 UTC, xp-1000 approved these changes

2020-09-29 12:36 UTC, xp-1000 commented
keep in mind this will lead to duplicate alerting if you also deploy database/mysql module (and monitor which give more frequent metrics).

2020-09-30 10:27 UTC, BzSpi commented on cloud/azure/mysql/detectors-mysql.tf
> +    description           = "is too high > ${var.replication_lag_threshold_critical}"
You **must** add unit :)

2020-09-30 10:29 UTC, BzSpi requested changes

2020-09-30 10:29 UTC, BzSpi commented on cloud/azure/mysql/variables.tf
> +  description = "Critical threshold for replication_lag detector"
```suggestion
  description = "Critical threshold in seconds for replication_lag detector"
```

2020-09-30 10:29 UTC, BzSpi commented on cloud/azure/mysql/variables.tf
> +  description = "Warning threshold for replication_lag detector"
```suggestion
  description = "Warning threshold in seconds for replication_lag detector"
```

2020-09-30 11:44 UTC, BzSpi approved these changes

2020-09-30 14:22 UTC, merged