Integration azure apim
claranet/terraform-signalfx-detectors pull request #199
Opened 2020-12-16 07:35 UTC by frederic-peraud

Init detectors for Azure Api Management Service.

2020-12-16 08:13 UTC, BzSpi requested changes

2020-12-16 08:13 UTC, BzSpi commented on modules/integration_azure-api-management-service/detectors-api_management_service.tf
> +        signal = data('Requests', filter=base_filter and ${module.filter-tags.filter_custom})${var.heartbeat_aggregation_function}.publish('signal')
I don't think request is a good metric for the healthcheck since an unused Api Management will trigger an alert.
Maybe `NetworkConnectivity` ?

2020-12-16 08:13 UTC, BzSpi commented on modules/integration_azure-api-management-service/variables.tf
> +  default     = ".mean(over='5m')"
`min` instead of `mean` ?

2020-12-16 08:13 UTC, BzSpi commented on modules/integration_azure-api-management-service/variables.tf
> +  default     = "5m"
A high usage of the API Management for 5 minutes may be too sensitive.

2020-12-16 08:13 UTC, BzSpi commented on modules/integration_azure-api-management-service/variables.tf
> +  default     = ".mean(over='5m')"
`min` instead of `mean` ?

2020-12-16 08:13 UTC, BzSpi commented on modules/integration_azure-api-management-service/variables.tf
> +  default     = ".mean(over='5m')"
`min` instead of `mean` ?

2020-12-16 09:13 UTC, Shr3ps requested changes

2020-12-16 09:13 UTC, Shr3ps commented on modules/integration_azure-api-management-service/detectors-api_management_service.tf
> +  name = format("%s %s", local.detector_name_prefix, "Azure Api Management Service Heartbeat")
What about API instead of Api in all detector names?

2020-12-21 10:22 UTC, BzSpi requested changes

2020-12-21 10:22 UTC, BzSpi commented on modules/integration_azure-api-management-service/variables.tf
> +  default     = 90
```suggestion
  default     = 95
```

2020-12-21 10:22 UTC, BzSpi commented on modules/integration_azure-api-management-service/variables.tf
> +  default     = 80
```suggestion
  default     = 90
```
An API Management service working at 80% of its capacity is a well sized resource in my opinion. :)

2021-01-07 18:37 UTC, xp-1000 approved these changes

2021-01-11 16:01 UTC, Shr3ps approved these changes

2021-01-11 16:14 UTC, merged