#123 [Azure] Application Gateway - capacity detector
claranet/terraform-signalfx-detectors pull request #202
Opened 2020-12-18 14:14 UTC by Shr3ps

2020-12-21 10:19 UTC, BzSpi requested changes
We should document how to find the `capacity_units_threshold_major` value since this concept is hardly understandable in my opinion.

2020-12-31 14:47 UTC, Shr3ps commented
> 
> 
> We should document how to find the `capacity_units_threshold_major` value since this concept is hardly understandable in my opinion.

done :)

2021-01-04 14:35 UTC, BzSpi approved these changes

2021-01-04 14:40 UTC, xp-1000 approved these changes

2021-01-04 14:41 UTC, merged