#123 [Azure] Event Hub - capacity detector
claranet/terraform-signalfx-detectors pull request #204
Opened 2020-12-18 16:21 UTC by Shr3ps

2020-12-21 10:15 UTC, BzSpi requested changes

2020-12-21 10:15 UTC, BzSpi commented on modules/integration_azure-event-hub/conf/01-capacity-throttling.yaml
> +    threshold: 80
```suggestion
    threshold: 0
```
We should be warned if we have any throttled request.

2020-12-21 10:15 UTC, BzSpi commented on modules/integration_azure-event-hub/conf/01-capacity-throttling.yaml
> +    threshold: 90
```suggestion
    threshold: 10
```
Not sure if 10% is a good threshold but 90% is way to high.

2020-12-21 10:15 UTC, BzSpi commented on modules/integration_azure-event-hub/conf/01-capacity-throttling.yaml
> +transformation: ".max(over='15m')"
```suggestion
transformation: ".min(over='15m')"
```
To avoid any spike.

2020-12-22 15:30 UTC, xp-1000 commented
please see https://github.com/claranet/terraform-signalfx-detectors/pull/217 for a fix on deadlink

2020-12-23 16:33 UTC, BzSpi commented on modules/integration_azure-event-hub/common-modules.tf
> +../../common/module/modules.tf
The common module use `env` and `sfx_monitored` filter but we want `azure_tag_env` and `azure_tag_sfx_monitored`.

2021-01-04 14:00 UTC, xp-1000 requested changes

2021-01-04 14:00 UTC, xp-1000 commented on modules/integration_azure-event-hub/conf/01-capacity-throttling.yaml
> +  warning:
is it really useful / desirable to have such a lot of severities ?

the role of this repo is also to advice a relevant severity for each detector created following our https://github.com/claranet/terraform-signalfx-detectors/wiki/Notifications-binding.

2021-01-04 14:33 UTC, BzSpi commented on modules/integration_azure-event-hub/conf/01-capacity-throttling.yaml
> +    threshold: 1
With a strict comparison, we can set 0 as value.

2021-01-11 16:22 UTC, xp-1000 approved these changes
LGTM

2021-01-11 16:23 UTC, merged