#203 improve Makefile with a dedicated target to generate a module
claranet/terraform-signalfx-detectors pull request #230
Opened 2021-01-05 17:22 UTC by Shr3ps

Usage: 

```bash
make module-update modules/smart-agent_couchbase
```

2021-01-05 17:27 UTC, xp-1000 reviewed
why not add an alias

2021-01-05 17:30 UTC, xp-1000 requested changes

2021-01-05 17:30 UTC, xp-1000 commented on Makefile
> +	CI=true ./scripts/module/gen_doc.sh $(COMMAND_ARGS)
```suggestion
module-update: modules lint
```

2021-01-06 08:37 UTC, xp-1000 approved these changes

2021-01-06 19:13 UTC, xp-1000 commented
@Shr3ps I pushed a couple of changes on Makefile (and updated the related doc: https://github.com/claranet/terraform-signalfx-detectors/blob/203_makefile_improve/docs/development.md#tldr) which should cover what you need in addition to make the usage easier (I hope).

what do you think?

2021-01-06 19:14 UTC, xp-1000 approved these changes

2021-01-07 11:03 UTC, xp-1000 commented
- all targets now start with an "action" (init, check, update..)
- targets are now long (but bash completion is installed on the dev env)
- it produces an human understanding sentence (update module doc)
- targets for deadlinks and spell checks added
- the special target update-module add the check-module one to get a
  full ready PR
- CI and doc updated

PR ready for reviews

2021-01-07 13:04 UTC, jcabeza approved these changes

2021-01-07 13:17 UTC, Gati0 approved these changes

2021-01-07 14:28 UTC, Shr3ps commented on docs/development.md
> +* as soon as you make a change on a module, run `make update-module` command.
```suggestion
* as soon as you make any change on a module, run `make update-module` command to update every generated files.
```

2021-01-07 14:28 UTC, Shr3ps commented on docs/development.md
> +$ MODULE_NAME="my-new-module" # use comma separated string to name your module
```suggestion
$ MODULE_NAME="my-new-module" # use dash separated word to name your module
```

2021-01-07 14:28 UTC, Shr3ps commented on docs/development.md
> +$ echo "Full update the module (doc, code, add/remove/change detectors ..)"
```suggestion
$ echo "Full update the module (doc, terraform code, add/remove/change detectors...)"
```

2021-01-07 14:28 UTC, Shr3ps commented on docs/development.md
> +will take care to regenerate code, documentation and even check the module to be sure to pass the CI.
```suggestion
will take care of regenerating code, documentation and even check and validate the module to pass the CI.
```

2021-01-07 14:28 UTC, Shr3ps commented on docs/development.md
> +You seen above the `update-module` and `init-module` `make` targets which are very common
```suggestion
You have seen above the `update-module` and `init-module` `make` targets which are very common 
```

2021-01-07 18:22 UTC, merged