kubernetes-common: fix OMMKilled detector
claranet/terraform-signalfx-detectors pull request #241
Opened 2021-01-25 09:13 UTC by NSenaud

Add .max(over='1m') to avoid triggering alert repeatedly

2021-01-25 12:12 UTC, xp-1000 requested changes

2021-01-25 12:12 UTC, xp-1000 commented on modules/smart-agent_kubernetes-common/detectors-kubernetes-common.tf
> +    signal = data('kubernetes.container_ready', filter=filter('container_status', 'terminated') and filter('container_status_reason', 'OOMKilled') and ${module.filter-tags.filter_custom})${var.oom_ki
I prefer you use the available `oom_killed_transformation_function` variable and set a default value instead of hardcode this here

2021-01-25 17:27 UTC, xp-1000 requested changes
seems good thanks

feel free to add a note about this in the readme it could be valuable to understand why this default value

2021-01-25 17:28 UTC, xp-1000 approved these changes

2021-01-26 08:46 UTC, NSenaud commented
Great! I added a note in README, rebased the branch and squashed commits.

2021-01-26 20:05 UTC, merged