Datafactory
claranet/terraform-signalfx-detectors pull request #242
Opened 2021-01-25 09:38 UTC by nicolasvion

adding some datafactory detectors

2021-01-25 09:53 UTC, Shr3ps requested changes

2021-01-25 09:53 UTC, Shr3ps commented on modules/integration_azure-datafactory/common-locals.tf
> +locals {
Why not keeping the symbolic link generated by bootstrap?

2021-01-25 09:53 UTC, Shr3ps commented on modules/integration_azure-datafactory/common-variables.tf
> +# Global
Why not keeping the symbolic link generated by bootstrap?

2021-01-25 09:53 UTC, Shr3ps commented on modules/integration_azure-datafactory/common-versions.tf
> +terraform {
Why not keeping the symbolic link generated by bootstrap?

2021-01-25 09:53 UTC, Shr3ps commented on modules/integration_azure-datafactory/detectors-datafactory.tf
> +        C = data('ActivityCancelledRuns', extrapolation="zero", rollup='sum',filter=base_filter and ${module.filter-tags.filter_custom})${var.adf_activity_run_aggregation_function}
C is never used?

2021-01-25 09:53 UTC, Shr3ps commented on modules/integration_azure-datafactory/detectors-datafactory.tf
> +        C = data('PipelineCancelledRuns', extrapolation="zero", rollup='sum',filter=base_filter and ${module.filter-tags.filter_custom})${var.adf_pipeline_run_aggregation_function}
C is never used?

2021-01-25 09:53 UTC, Shr3ps commented on docs/severity.md
> +|Azure DataFactory Activity Rate Status|X|X|-|-|-|
No heartbeat detector for this resource?

2021-01-25 10:01 UTC, xp-1000 requested changes
most of the formula seem not correct or at least there is a useless signal in them.

I see you define Critical / Major everywhere, are you sure all detectors here are all equally important ? (and require a critical severity?).

Also you use lasting everywhere, is there really necessary / wanted ?

2021-01-25 10:07 UTC, BzSpi commented
Can you please the detectors generation from yaml files as its easier to read and to maintain ?

2021-01-28 16:11 UTC, BzSpi requested changes
We can also add a detector that checks the resources count against the max since metrics are available.

2021-01-28 16:11 UTC, BzSpi commented on modules/integration_azure-datafactory/conf/04-adf-integration-available-memory.yaml
> +transformation: ".min(over='5m')"
Seems quite short since low memory is not critical for this use case.

2021-01-28 16:11 UTC, BzSpi commented on modules/integration_azure-datafactory/common-modules.tf
> +../../common/module/modules.tf
The common modules are not so common and this file must be overriden for Azure detectors.
See https://github.com/claranet/terraform-signalfx-detectors/pull/232/files#diff-bb6d827b32ed7a279afebaba971ac107164c91173cdf2a40cae959f6163d03a4

2021-01-28 16:11 UTC, BzSpi commented on modules/integration_azure-datafactory/conf/01-adf-activity-run.yaml
> +aggregation: ".sum(by=['azure_resource_name', 'azure_resource_group_name', 'azure_region'])"
Aggregation should be done per pipeline and not per resource.

2021-01-28 16:11 UTC, BzSpi commented on modules/integration_azure-datafactory/conf/02-adf-pipeline-run.yaml
> +aggregation: ".sum(by=['azure_resource_name', 'azure_resource_group_name', 'azure_region'])"
Aggregation should be done per pipeline and not per resource.

2021-01-28 16:11 UTC, BzSpi commented on modules/integration_azure-datafactory/conf/03-adf-trigger-run.yaml
> +aggregation: ".sum(by=['azure_resource_name', 'azure_resource_group_name', 'azure_region'])"
Aggregation should be done per pipeline and not per resource.

2021-02-03 10:31 UTC, Shr3ps commented on common/module/modules.tf
> +  filter_defaults        = "filter('azure_tag_env', '${var.environment}') and filter('azure_tag_sfx_monitored', 'true')"
ooops, no, you must not edit the common module used by everyone XD

2021-02-11 10:55 UTC, Shr3ps requested changes

2021-02-11 10:55 UTC, Shr3ps commented on modules/integration_azure-datafactory/conf/01-adf-activity-run.yaml
> +aggregation: ".sum(by=['name'])"
hum, is this enough? what if you have multiple pipeline with the same name il multiple rg/regions?

2021-02-17 11:25 UTC, xp-1000 requested changes
overall seems good for me, see comments for requested changes including:
- useless rollup to delete
- undesirable changes out of scope (e.g. main readme)
- rename modules file

also I doubt that all percentage based detectors have the same combination of thresholds and severity but I cannot say it is up to you.

2021-02-17 11:25 UTC, xp-1000 commented on modules/integration_azure-datafactory/conf/02-adf-pipeline-run.yaml
> +    rollup: rate
while you make a percentage the default rollum sum will give the same result and it seems to be a most relevant value for troubleshooting

2021-02-17 11:25 UTC, xp-1000 commented on modules/integration_azure-datafactory/conf/02-adf-pipeline-run.yaml
> +    rollup: rate
while you make a percentage the default rollum sum will give the same result and it seems to be a most relevant value for troubleshooting

2021-02-17 11:25 UTC, xp-1000 commented on modules/integration_azure-datafactory/conf/03-adf-trigger-run.yaml
> +    rollup: rate
while you make a percentage the default rollum sum will give the same result and it seems to be a most relevant value for troubleshooting

2021-02-17 11:25 UTC, xp-1000 commented on modules/integration_azure-datafactory/conf/03-adf-trigger-run.yaml
> +    rollup: rate
while you make a percentage the default rollum sum will give the same result and it seems to be a most relevant value for troubleshooting

2021-02-17 11:25 UTC, xp-1000 commented on modules/integration_azure-datafactory/conf/04-adf-integration-available-memory.yaml
> +    threshold: 512
I think we need either a note in readme to explain why this value makes sens for a general usage or to remove it else to let the user customize the value suited to its need.

2021-02-17 11:25 UTC, xp-1000 commented on modules/integration_azure-datafactory/conf/04-adf-integration-available-memory.yaml
> +    rollup: average
this is the defaut, you can delete it

2021-02-17 11:25 UTC, xp-1000 commented on modules/integration_azure-datafactory/conf/05-adf-integration-cpu-percentage.yaml
> +    rollup: average
this is the defaut, you can delete it

2021-02-17 11:25 UTC, xp-1000 commented on modules/integration_azure-datafactory/conf/05-adf-integration-cpu-percentage.yaml
> +    threshold: 90 # 512MB
remove comment

2021-02-17 11:25 UTC, xp-1000 commented on modules/integration_azure-datafactory/conf/05-adf-integration-cpu-percentage.yaml
> +    threshold: 80 # 256MB
remove comment

2021-02-17 11:25 UTC, xp-1000 commented on modules/integration_azure-datafactory/common-modules.tf
> +module "filter-tags" {
while this is not the common file it should simple be named `modules.tf`

2021-02-17 16:28 UTC, xp-1000 approved these changes
looks good for me thanks

2021-02-18 15:59 UTC, Shr3ps approved these changes

2021-02-22 18:42 UTC, merged