init blob detectors - disabled by default, need explicit activation
claranet/terraform-signalfx-detectors pull request #245
Opened 2021-02-11 09:31 UTC by nicolasvion

- adding blob storage detectors
- disabled by default, need explicit activation because of some stability pb
- customers' request

2021-02-11 10:53 UTC, Shr3ps requested changes

2021-02-11 10:53 UTC, Shr3ps commented on modules/integration_azure-storage-account-blob/conf/01-requests-rate-status.yaml
> +    filter: "not filter('responsetype', 'Success')"
hum, filter on Failed?

2021-02-11 10:53 UTC, Shr3ps commented on modules/integration_azure-storage-account-blob/conf/02-latency-e2e.yaml
> +    threshold: 2
2s of latency by default? don't you think it's low by default?

but not very important, we can override this value with the terraform variable.

2021-02-11 10:53 UTC, Shr3ps commented on modules/integration_azure-storage-account-blob/conf/readme.yaml
> +documentations:
A real link here would be great :)

2021-02-17 11:28 UTC, xp-1000 requested changes
just to minor comments

2021-02-17 11:28 UTC, xp-1000 commented on modules/integration_azure-storage-account-blob/common-modules.tf
> +module "filter-tags" {
should be named `modules.tf`

2021-02-17 11:28 UTC, xp-1000 commented on modules/integration_azure-storage-account-blob/conf/readme.yaml
> +  [Microsoft.Storage/storageAccounts](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftclassicstoragestorageaccountsblobservices) namespace.
I would add a note about disabled detectors (why disabled by default and when to use them)

2021-02-17 16:32 UTC, xp-1000 approved these changes
LGTM thanks

2021-02-18 16:31 UTC, Shr3ps approved these changes

2021-02-22 18:35 UTC, merged