improve cassandra detectors
claranet/terraform-signalfx-detectors pull request #264
Opened 2021-03-23 10:44 UTC by Gati0

Currently, the aggregation is done on the delta and not on the latency itself. 
This can lead to weird results we think.
This commit fixes that.

2021-03-23 12:57 UTC, BzSpi approved these changes

2021-03-23 13:02 UTC, Shr3ps approved these changes
LGTM

2021-03-23 14:51 UTC, xp-1000 commented
I would like to have more information about these weird results before to merge

2021-04-15 18:17 UTC, xp-1000 commented
see related issue here: https://github.com/claranet/terraform-signalfx-detectors/issues/278

if you agree with its description the right fix here would be to create a new "separated" variable for transformation at "formula" level (in addition the current transformation variable applied for each "metric" level).

If you go to this way, I will implement this change in the generator following your naming to make this available for all cases and fully integrated in our conventions.

also this fix (no matter how implemented) should be applied to all other "latency" detectors of this module in my opinion.

2021-04-15 18:21 UTC, xp-1000 requested changes
I think it is safer to use a separate and new transformation variable for final signal as explained in #278 which will need to propagate this to all existing similar scenario.

2021-08-09 16:39 UTC, xp-1000 commented
without answers from author to my question I convert this PR to draft

2021-08-23 15:38 UTC, xp-1000 commented
I close because https://github.com/claranet/terraform-signalfx-detectors/pull/323 should bring similar improvements

2021-08-23 15:38 UTC, closed without merging