Add deadlettered messages detector
claranet/terraform-signalfx-detectors pull request #296
Opened 2021-06-28 16:15 UTC by Davidh-claranet

I added a detector for the Deadlettered messages metric.
It is my first detector from scratch.
Advices are welcome.
David.

2021-06-28 16:32 UTC, xp-1000 reviewed
Hello, thanks for the contribution.

My first advices would be to rebase your branch from master to get last updates (required for merge) and to use the yaml generator instead of writing the code manually this should ease your work to create a full compliant detector in addition to the review.

check this documentation https://github.com/claranet/terraform-signalfx-detectors/blob/master/docs/development.md#tldr for more information. In short, you just have to:

1. create a new `[0-9][0-9]-mydetector.yaml` file into the `conf` dir of the exiting module which will be used after to automatically generate the changes. following configuration available here : https://github.com/claranet/terraform-signalfx-detectors/blob/master/scripts/templates/values.yaml (sort of helm chart).
1. use options available on https://github.com/claranet/terraform-signalfx-detectors/blob/master/scripts/templates/values.yaml to update this yaml import equivalent configuration than your current code
1. remove your manual changes
1. run docker and then enter in dev env with `make`
1. run `make update-module *azure-service-bus*`
1. commit and push and the CI should be happy

2021-06-29 12:04 UTC, xp-1000 requested changes

2021-06-29 12:04 UTC, xp-1000 commented on modules/integration_azure-service-bus/detectors-service-bus.tf
> +        detect(when(signal > threshold(${var.deadlettered_messages_threshold_critical}), lasting="${var.deadlettered_messages_timer}")).publish('CRIT')
do not reverse the major condition in the critical one will lead to duplicated alerts when critical threshold is reached.

2021-06-29 13:41 UTC, xp-1000 requested changes
your fork still require to be updated

2021-06-29 13:41 UTC, xp-1000 commented on modules/integration_azure-service-bus/detectors-service-bus.tf
> +        detect(when(signal > threshold(${var.deadlettered_messages_threshold_major}), lasting="${var.deadlettered_messages_timer}") and when(signal <= ${var.deadlettered_messages_threshold_critical})
double publish functions here

2021-06-29 14:57 UTC, Davidh-claranet commented on modules/integration_azure-service-bus/detectors-service-bus.tf
> +        detect(when(signal > threshold(${var.deadlettered_messages_threshold_major}), lasting="${var.deadlettered_messages_timer}") and when(signal <= ${var.deadlettered_messages_threshold_critical})
Sorry, a copy/paste error....

2021-06-30 10:59 UTC, xp-1000 approved these changes
LGTM, again .. you have to refresh your fork.

waiting for azure owners (@BzSpi or @Shr3ps) reviews before to merge

2021-06-30 11:30 UTC, BzSpi requested changes
A relative check (number of deadlettered messages compared to the overall messages count) may be a better implementation IMHO.

2021-06-30 11:30 UTC, BzSpi commented on modules/integration_azure-service-bus/detectors-service-bus.tf
> +  name = format("%s %s", local.detector_name_prefix, "Azure Service Bus deadlettered messages")
```suggestion
  name = format("%s %s", local.detector_name_prefix, "Azure Service Bus deadlettered messages count")
```

2021-06-30 11:30 UTC, BzSpi commented on modules/integration_azure-service-bus/variables.tf
> +  description = "Notification recipients list per severity overridden for active_connections detector"
```suggestion
  description = "Notification recipients list per severity overridden for deadlettered_messages detector"
```

2021-06-30 11:30 UTC, BzSpi commented on modules/integration_azure-service-bus/variables.tf
> +  description = "Disable critical alerting rule for active_connections detector"
```suggestion
  description = "Disable critical alerting rule for deadlettered_messages detector"
```

2021-06-30 11:30 UTC, BzSpi commented on modules/integration_azure-service-bus/variables.tf
> +  description = "Disable critical alerting rule for active_connections detector"
```suggestion
  description = "Disable critical alerting rule for deadlettered_messages detector"
```

2021-06-30 11:30 UTC, BzSpi commented on modules/integration_azure-service-bus/variables.tf
> +  description = "Disable all alerting rules for active_connections detector"
```suggestion
  description = "Disable all alerting rules for deadlettered_messages detector"
```

2021-06-30 11:30 UTC, BzSpi commented on modules/integration_azure-service-bus/variables.tf
> +  default     = ".mean(by=['azure_resource_name', 'azure_resource_group_name', 'azure_region', 'entityname'])"
```suggestion
  default     = ".mean(by=[' entityname ', 'azure_resource_name', 'azure_resource_group_name', 'azure_region', 'entityname'])"
```

2021-07-06 13:17 UTC, Davidh-claranet commented on modules/integration_azure-service-bus/detectors-service-bus.tf
> +  name = format("%s %s", local.detector_name_prefix, "Azure Service Bus deadlettered messages")
Done

2021-07-06 13:19 UTC, Davidh-claranet commented on modules/integration_azure-service-bus/variables.tf
> +  description = "Disable critical alerting rule for active_connections detector"
Done

2021-07-06 13:19 UTC, Davidh-claranet commented on modules/integration_azure-service-bus/variables.tf
> +  description = "Disable all alerting rules for active_connections detector"
Done

2021-07-06 13:20 UTC, Davidh-claranet commented on modules/integration_azure-service-bus/variables.tf
> +  default     = ".mean(by=['azure_resource_name', 'azure_resource_group_name', 'azure_region', 'entityname'])"
Done

2021-07-06 15:02 UTC, Davidh-claranet commented
I did the requested changes and the detector signal is now a rate of the deadletteredmessage/messages (percentage)

2021-07-20 10:25 UTC, xp-1000 commented
ping @BzSpi for a review

2021-07-23 08:52 UTC, Davidh-claranet commented
Please do not validate this pull request
I have to do changes.....

2021-07-27 19:13 UTC, Davidh-claranet commented
the detector signal is now the deadletteredmessage count

2021-08-09 16:34 UTC, xp-1000 commented
> Please do not validate this pull request
> I have to do changes.....

ok @Davidh-claranet I let you make the PR ready when it is good for you, I convert it as draft for now

2021-08-24 08:23 UTC, Davidh-claranet commented
This PR is ready for merge....

2021-11-05 14:07 UTC, Davidh-claranet commented
ok pour merger !

2021-11-05 14:14 UTC, Shr3ps approved these changes
Seems ok, too bad this is not created via yml conf file

2021-11-15 12:15 UTC, xp-1000 requested changes
sadly this PR is a bit old and the hcl code to create detectors is not up to date anymore because templating has evolved in previous release published since the PR creation.

this is why it is better to use the generator which will take care of updating code to always match templating rules, especially useful for long running PR like this one.

2021-11-15 13:36 UTC, xp-1000 commented
> sadly this PR is a bit old and the hcl code to create detectors is not up to date anymore because templating has evolved in previous release published since the PR creation.
> 
> this is why it is better to use the generator which will take care of updating code to always match templating rules, especially useful for long running PR like this one.

see https://github.com/claranet/terraform-signalfx-detectors/pull/345 for implementation with generator and what was missing here for your information (transformation function, lasting ..)

2021-11-17 12:52 UTC, closed without merging