Azure FrontDoor v2 detectors module
claranet/terraform-signalfx-detectors pull request #370
Opened 2022-01-20 15:46 UTC by maxpoullain

- Add Azure FrontDoor Premium/Standard detectors via [FAME](https://github.com/claranet/fame) metrics.

2022-01-20 16:30 UTC, Shr3ps commented
Hum, the directory name cannot start with "integration" since it's not based on the Azure integration 🤔 
`claranet`? `fame`? `custom`?

2022-01-20 16:33 UTC, Shr3ps submitted a review, later dismissed

2022-01-20 16:33 UTC, Shr3ps commented on modules/integration_azure-frontdoor-v2/conf/readme.yaml
> +  Here are the must have FAME queries for your Front Door v2 resources :
```suggestion
  Here are the must have FAME queries for your Front Door v2 resources:
```

2022-05-10 07:51 UTC, xp-1000 commented
@Shr3ps @BzSpi can you review this?

2022-07-04 14:17 UTC, Shr3ps approved these changes

2022-07-04 15:01 UTC, BzSpi requested changes

2022-07-04 15:01 UTC, BzSpi commented on modules/fame_azure-frontdoor-v2/conf/02-probes_errors.yaml
> +    filter: "filter('http_status_code', '5**') or filter('http_status_code', '404') or filter('result', 'OriginTimeout') or filter('result', 'DNSNameNotResolved')"
Can't we heck if status != 200 instead ?

2022-07-04 15:01 UTC, BzSpi commented on modules/fame_azure-frontdoor-v2/conf/03-cache_hit_rate.yaml
> +    threshold: 60
I'm not sure having a cache hit rate < 60% should be a global alerting rule.

2023-09-08 12:28 UTC, BzSpi commented
We will fallback to Azure metrics

2023-09-08 12:28 UTC, closed without merging