Change permitted.scale(1024) -> permitted.scale(60), need to be in se…
claranet/terraform-signalfx-detectors pull request #417
Opened 2022-06-02 08:49 UTC by gburgaud-claranet

Formula 
`    signal = (metered/permitted.scale(60)).scale(100).publish('signal')
`
is incorrect.
PermittedThroughput need to be converted in second

https://docs.aws.amazon.com/efs/latest/ug/monitoring-metric-math.html#metric-math-throughput-utilization

2022-06-02 14:49 UTC, pdecat approved these changes
LGTM :)

2022-06-22 16:55 UTC, tchernomax approved these changes
LGTM

2022-06-22 16:59 UTC, tchernomax requested changes
You change detectors-gen.tf → you need to change [module/in](https://github.com/claranet/terraform-signalfx-detectors/blob/master/modules/integration_aws-efs/conf/05-permitted-throughput.yaml#L16) instead and run:
```
# to enter the docker container
make
# to generate the modules/integration_aws-efs/detectors-gen.tf from the conf
make update-module
```

2022-07-08 08:13 UTC, pdecat approved these changes

2022-07-08 13:09 UTC, merged