Add Azure CDN detector
claranet/terraform-signalfx-detectors pull request #444
Opened 2022-10-31 11:02 UTC by Gati0

Add the Azure CDN classic integration module.
This module aims to supervise the CDN resource of Azure (microsoft.cdn/profiles). For the moment only the latency is supervised.

2022-10-31 12:49 UTC, BzSpi requested changes

2022-10-31 12:49 UTC, BzSpi commented on modules/integration_azure-cdn/conf/00-latency.yaml
> +    threshold: 1500
Are thresholds inverted ?

2022-10-31 12:49 UTC, BzSpi commented on modules/integration_azure-cdn/conf/00-latency.yaml
> +    rollup: max
This should be removed, It would make the metric less readable in detector and also trigger more alerts than needed.

2022-10-31 12:49 UTC, BzSpi commented on modules/integration_azure-cdn/conf/00-latency.yaml
> +
Add `value_unit` as described here https://github.com/claranet/terraform-signalfx-detectors/blob/master/scripts/templates/values.yaml#L99

2022-10-31 12:49 UTC, BzSpi commented on modules/integration_azure-cdn/conf/readme.yaml
> +
Please add a link to MS doc https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcdnprofiles

2022-11-16 09:10 UTC, BzSpi commented on modules/integration_azure-cdn/conf/readme.yaml
> +
I don't see any change here :thinking:

2023-02-22 15:06 UTC, Shr3ps approved these changes

2023-02-22 15:52 UTC, merged