Key vault latency detector: remove critical status
claranet/terraform-signalfx-detectors pull request #465
Opened 2023-04-05 12:58 UTC by freezeeedos

This commit is to remove the critical status from the keyvault latency detector, and use only major and minor

2023-04-05 14:01 UTC, BzSpi requested changes

2023-04-05 14:01 UTC, BzSpi commented on modules/integration_azure-key-vault/detectors-keyvault.tf
> +    disabled              = coalesce(var.api_latency_disabled, var.detectors_disabled)
Also, missing variable.

```suggestion
    disabled              = coalesce(var.api_latency_disabled_minor, var.api_latency_disabled, var.detectors_disabled)
```

2023-04-05 14:16 UTC, BzSpi approved these changes

2023-04-07 09:31 UTC, zfiel approved these changes

2023-04-18 08:11 UTC, merged