Azure Backup detectors for VM & File Shares
claranet/terraform-signalfx-detectors pull request #466
Opened 2023-04-06 09:58 UTC by BzSpi

2023-04-06 10:04 UTC, Shr3ps requested changes

2023-04-06 10:04 UTC, Shr3ps commented on modules/integration_azure-backup/common-filters.tf
> +locals {
must be a symlink to common

2023-04-06 10:15 UTC, Shr3ps approved these changes

2023-04-07 09:27 UTC, alanbty approved these changes

2023-04-07 09:29 UTC, zfiel approved these changes

2023-04-07 12:20 UTC, BzSpi commented
Back in Draft, behavior is not the one expected.

2023-04-11 08:11 UTC, merged