Detectors for Prometheus varnish exporter
claranet/terraform-signalfx-detectors pull request #475
Opened 2023-06-16 16:22 UTC by rsicart

Same detectors configured for smartagent varnish module, but with a prometheus exporter source.

2023-06-20 08:26 UTC, JMHAUTBOIS-Claranet requested changes
Looks like you need to launch again the generator after applying changes.

2023-06-20 08:26 UTC, JMHAUTBOIS-Claranet commented on modules/prometheus-exporter_varnish/conf/readme.yaml
> +source_doc:
There's an error because of the missing pipe : 

```suggestion
source_doc: |
```

2023-06-20 08:26 UTC, JMHAUTBOIS-Claranet commented on modules/prometheus-exporter_varnish/conf/readme.yaml
> +
Missing ending backticks :
````suggestion
```
````

2023-06-29 12:04 UTC, rsicart commented
@JMHAUTBOIS-Claranet @haedri do you believe that this PR will be good for milestone v1.25.0?

2023-07-03 14:53 UTC, JMHAUTBOIS-Claranet approved these changes

2023-07-03 14:53 UTC, merged