fix: remove pointless CPU transformation
claranet/terraform-signalfx-detectors pull request #520
Opened 2023-11-15 17:12 UTC by Tulux

2023-11-15 19:16 UTC, pdecat commented
Could you please provide some rationale about this change?

2023-11-16 08:08 UTC, Tulux commented
@pdecat I added note in first comment

2023-11-16 08:17 UTC, pdecat commented
The "idea" of this detector is to raise an alert if the CPU usage never goes down for a long period.
We do not want to alert on every spike.
Also, using CPU is a good thing as we are paying for it.

If this does not fit your use case, just customize the variable.

2023-11-16 12:24 UTC, Tulux commented
> The "idea" of this detector is to raise an alert if the CPU usage never goes down for a long period. We do not want to alert on every spike. Also, using CPU is a good thing as we are paying for it.

This should be done in the `detect()` part where you can set a period detection of 1h via `when()` which results in a same behavior. Transformation functions are calculated after detector time aggregation and they also hide the original metric which is a barrier for operational run.

> 
> If this does not fit your use case, just customize the variable.

Yep I did, however the point of this PR is to provide a correct default detector which brings original metric visualization.

2023-11-16 12:36 UTC, pdecat approved these changes
With the addition of a 1h duration, this is now way better.

LGTM!

2023-11-16 12:39 UTC, pdecat requested changes
Except the changes must be done in the configuration, not the generated files.

2023-11-16 14:44 UTC, Tulux commented on modules/smart-agent_system-common/variables-gen.tf
> -
done in [bcae613](https://github.com/claranet/terraform-signalfx-detectors/pull/520/commits/bcae6139af7bd470da0ca0cdc27af51db54a8afd)

2023-11-16 14:59 UTC, pdecat approved these changes
LGTM!

2023-11-16 15:04 UTC, merged