AZ-1269: New detector for VPN Tunnels' FAME Query
claranet/terraform-signalfx-detectors pull request #534
Opened 2023-12-05 16:48 UTC by jmapro

- [ ] Depend on internal MR on RUN module.

2023-12-08 09:30 UTC, BzSpi requested changes

2023-12-08 09:30 UTC, BzSpi commented on modules/fame_azure-vpn/conf/02-tunnel-status.yaml
> +transformation: ".fill()"
It seems to me that `fill` without value is useless.
Also, use extrapolation instead.

2023-12-08 09:30 UTC, BzSpi commented on modules/fame_azure-vpn/conf/02-tunnel-status.yaml
> +
```suggestion
    metric: fame.azure.virtual_network_gateway.tunnel_status
    extrapolation: 'zero'
```

2023-12-08 09:30 UTC, BzSpi commented on modules/fame_azure-vpn/conf/02-tunnel-status.yaml
> +  critical:
No major alert ? With a smaller lasting for example.

2023-12-08 09:30 UTC, BzSpi commented on modules/fame_azure-vpn/conf/02-tunnel-status.yaml
> +id: tunnelstatus
```suggestion
id: tunnel_status
```

2023-12-08 10:40 UTC, BzSpi commented on modules/fame_azure-vpn/conf/02-tunnel-status.yaml
> +
use fill instead to have better control of the duration.

2024-12-13 10:25 UTC, BzSpi approved these changes

2024-12-13 10:45 UTC, haedri commented on modules/fame_azure-vpn/conf/02-tunnel-status.yaml
> +    lasting_duration: '10m'
It's missing a dependency here I think

2024-12-13 12:22 UTC, merged